GET http://localhost:4000/api/products

###
GET http://localhost:4000/api/products/61aef40c17f62efb9a6c46dc

###
POST http://localhost:4000/api/users/login
Content-Type: application/json

{
    "email":"brad@xyz.com",
    "password":"123456"
}

###
POST http://localhost:4000/api/users/register
Content-Type: application/json

{
    "name": "Brad Traversy",
    "email":"brad@xyz.com",
    "password": "123456"
}

###
GET http://localhost:4000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYWVmNDBjMTdmNjJlZmI5YTZjNDZkNSIsImlhdCI6MTY0MDA2MDkxNCwiZXhwIjoxNjQyNjUyOTE0fQ.41kacs21Lt7lhg_zIcGWNdqOdMroTcEZS76RMzNMDws

###
PUT  http://localhost:4000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYjVkYjgzNjI2YjU4NjM5MmNmMjZjMyIsImlhdCI6MTYzOTMyODg5MCwiZXhwIjoxNjQxOTIwODkwfQ.bkHyGZ4-aeHtb3h-NpqNBtK-KXPrtROyf2o9-cjSKL8
Content-Type: application/json

{
    "name": "Steven Smith"
}

###
GET http://localhost:4000/api/users/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYWVmNDBjMTdmNjJlZmI5YTZjNDZkNSIsImlhdCI6MTY0MDA2MDkxNCwiZXhwIjoxNjQyNjUyOTE0fQ.41kacs21Lt7lhg_zIcGWNdqOdMroTcEZS76RMzNMDws

###
DELETE http://localhost:4000/api/users/61c1891fce77b0162d0dab58
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYWVmNDBjMTdmNjJlZmI5YTZjNDZkNSIsImlhdCI6MTY0MDA2MDkxNCwiZXhwIjoxNjQyNjUyOTE0fQ.41kacs21Lt7lhg_zIcGWNdqOdMroTcEZS76RMzNMDws

###
GET http://localhost:4000/api/users/61c1891fce77b0162d0dab58
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYWVmNDBjMTdmNjJlZmI5YTZjNDZkNSIsImlhdCI6MTY0MDA2MDkxNCwiZXhwIjoxNjQyNjUyOTE0fQ.41kacs21Lt7lhg_zIcGWNdqOdMroTcEZS76RMzNMDws

###
PUT  http://localhost:4000/api/users/61c1891fce77b0162d0dab58
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYWVmNDBjMTdmNjJlZmI5YTZjNDZkNSIsImlhdCI6MTY0MDA2MDkxNCwiZXhwIjoxNjQyNjUyOTE0fQ.41kacs21Lt7lhg_zIcGWNdqOdMroTcEZS76RMzNMDws
Content-Type: application/json

{
    "email":"brad@abc.com",
    "adminStatus": true
}

###
GET http://localhost:4000/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYWVmNDBjMTdmNjJlZmI5YTZjNDZkNiIsImlhdCI6MTYzOTk5MDE2NCwiZXhwIjoxNjQyNTgyMTY0fQ.fafV8cqBokV69EZ1ssTsWL179jhSZaVN_qXoyqv_AvE

###
GET http://localhost:4000/api/orders/61bd7214a86656d8056ad07a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYjRhYTZkMTE4MjEzM2VhMGU1NmM4ZiIsImlhdCI6MTYzOTgwMzg2NywiZXhwIjoxNjQyMzk1ODY3fQ.MA5Yh5IbFyoSYmBkxDsxOTiEN_nbA0pciAg2iW-u_6M

###
GET http://localhost:4000/api/config/paypal

###
POST http://localhost:4000/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYjVkYjgzNjI2YjU4NjM5MmNmMjZjMyIsImlhdCI6MTYzOTQ1NTIzNiwiZXhwIjoxNjQyMDQ3MjM2fQ.Yf9294vKRXindCWcuG6x25KIs3RcIiFwdWn1fsKTh8c
Content-Type: application/json

{
    "orderItems": [
        {
            "itemID": "61aef40c17f62efb9a6c46df",
            "itemName": "Logitech G-Series Gaming Mouse",
            "itemImage": "/images/mouse.jpg",
            "price": 49.99,
            "quantity": 2
        },
        {
            "itemID": "61aef40c17f62efb9a6c46dc",
            "itemName": "iPhone 11 Pro 256GB Memory",
            "itemImage": "/images/phone.jpg",
            "price": 599.99,
            "quantity": 1
        }
    ],
    "shippingAddress": {
        "address": "42nd East Rd",
        "city": "New York NY",
        "country": "USA",
        "postCode": 14168
    },
    "paymentMethod": "PayPal",
    "shippingPrice": 0,
    "taxPrice": 57.59,
    "totalPrice": 607.98
}

###
POST http://localhost:4000/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYWVmNDBjMTdmNjJlZmI5YTZjNDZkNSIsImlhdCI6MTY0MDA2MDkxNCwiZXhwIjoxNjQyNjUyOTE0fQ.41kacs21Lt7lhg_zIcGWNdqOdMroTcEZS76RMzNMDws
Content-Type: application/json

{
    "name":"Test Product",
    "description": "Test Match Special",
    "brand": "Motorola",
    "category": "Feature Phones",
    "price": 89.90,
    "stocks": 18
}

###
DELETE  http://localhost:4000/api/products/61c49a043359c88f04a09914
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYWVmNDBjMTdmNjJlZmI5YTZjNDZkNSIsImlhdCI6MTY0MDA2MDkxNCwiZXhwIjoxNjQyNjUyOTE0fQ.41kacs21Lt7lhg_zIcGWNdqOdMroTcEZS76RMzNMDws

###
PUT   http://localhost:4000/api/products/61c4a43c3942cb354557642c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYWVmNDBjMTdmNjJlZmI5YTZjNDZkNSIsImlhdCI6MTY0MDA2MDkxNCwiZXhwIjoxNjQyNjUyOTE0fQ.41kacs21Lt7lhg_zIcGWNdqOdMroTcEZS76RMzNMDws
Content-Type: application/json

{
    "avgRating": 1.5
}