export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAILURE = 'ORDER_CREATE_FAILURE'
export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'

export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAILURE = 'ORDER_DETAILS_FAILURE'
export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'

export const ORDER_PAYMENT_SUCCESS = 'ORDER_PAYMENT_SUCCESS'
export const ORDER_PAYMENT_FAILURE = 'ORDER_PAYMENT_FAILURE'
export const ORDER_PAYMENT_REQUEST = 'ORDER_PAYMENT_REQUEST'
export const ORDER_PAYMENT_RESET = 'ORDER_PAYMENT_RESET'

export const ORDERS_GET_MINE_SUCCESS = 'ORDERS_GET_MINE_SUCCESS'
export const ORDERS_GET_MINE_FAILURE = 'ORDERS_GET_MINE_FAILURE'
export const ORDERS_GET_MINE_REQUEST = 'ORDERS_GET_MINE_REQUEST'

export const ORDERS_GET_ALL_SUCCESS = 'ORDERS_GET_ALL_SUCCESS'
export const ORDERS_GET_ALL_FAILURE = 'ORDERS_GET_ALL_FAILURE'
export const ORDERS_GET_ALL_REQUEST = 'ORDERS_GET_ALL_REQUEST'

export const ORDER_DELIVERY_SUCCESS = 'ORDER_DELIVERY_SUCCESS'
export const ORDER_DELIVERY_FAILURE = 'ORDER_DELIVERY_FAILURE'
export const ORDER_DELIVERY_REQUEST = 'ORDER_DELIVERY_REQUEST'
export const ORDER_DELIVERY_RESET = 'ORDER_DELIVERY_RESET'

export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS'
export const ORDER_DELETE_FAILURE = 'ORDER_DELETE_FAILURE'
