export const PRODUCTS_LIST_REQUEST = 'PRODUCTS_LIST_REQUEST'
export const PRODUCTS_LIST_SUCCESS = 'PRODUCTS_LIST_SUCCESS'
export const PRODUCTS_LIST_FAILURE = 'PRODUCTS_LIST_FAILURE'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAILURE = 'PRODUCT_DETAILS_FAILURE'

export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAILURE = 'PRODUCT_DELETE_FAILURE'
export const PRODUCT_DELETE_RESET = 'PRODUCT_DELETE_RESET'

export const PRODUCT_EDIT_REQUEST = 'PRODUCT_EDIT_REQUEST'
export const PRODUCT_EDIT_SUCCESS = 'PRODUCT_EDIT_SUCCESS'
export const PRODUCT_EDIT_FAILURE = 'PRODUCT_EDIT_FAILURE'
export const PRODUCT_EDIT_RESET = 'PRODUCT_EDIT_RESET'

export const IMAGE_UPLOAD_REQUEST = 'IMAGE_UPLOAD_REQUEST'
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS'
export const IMAGE_UPLOAD_FAILURE = 'IMAGE_UPLOAD_FAILURE'

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAILURE = 'PRODUCT_CREATE_FAILURE'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'
