export const PRODUCTS_LIST_REQUEST = 'PRODUCTS_LIST_REQUEST'
export const PRODUCTS_LIST_SUCCESS = 'PRODUCTS_LIST_SUCCESS'
export const PRODUCTS_LIST_FAILURE = 'PRODUCTS_LIST_FAILURE'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAILURE = 'PRODUCT_DETAILS_FAILURE'
